---
- name: Backend configuration
  hosts: localhost
  connection: local
  become: yes
  tasks: 
   - name: Disabling of nodejs
     ansible.builtin.command: "dnf module disable nodejs -y"

   - name: Enabling version:20 of nodejs
     ansible.builtin.command: dnf module enable nodejs:20 -y

   - name: Installing nodejs
     ansible.builtin.dnf:
      state: present
      name: nodejs 

   - name: Creating User
     ansible.builtin.user:
     

    