---
- name: mysql server configuration
  hosts: localhost
  become: yes
  tasks:
   - name: Installing mysql-server 
     ansible.builtin.dnf:
      name: mysql-server
      state: present
   - name: Enable and start mysql-server(mysqld)
     ansible.builtin.service:
      enabled: yes
      started: yes
      name: mysqld
   - name: Setting root password
     ansible.builtin.command: "mysql_secure_installation --set-root-pass ExpenseApp@1"    